### ISSUE TITLE
Password for sample files ?

### ISSUE THREAD

**Issue by ducthangbui** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#10]
Hi,
Could you give me password for sample files in this repository ?

Thank you

**Comment by CaledoniaProject** [comment]
@CyberMonitor You might consider add this to the README.md, I've seen too many people asking for the password of sample files, e.g

https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/issues/9

**Comment by CyberMonitor** [comment]
Thank you for your suggestion, add to README.md biw
