### ISSUE TITLE
Twisted Panda: Chinese APT espionage operation against Russian’s state-owned defense institutes

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#100]
https://research.checkpoint.com/2022/twisted-panda-chinese-apt-espionage-operation-against-russians-state-owned-defense-institutes/

**Comment by CyberMonitor** [comment]
thank the data,  update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.05.19.Twisted_Panda
