### ISSUE TITLE
Kaspersky: WinDealer malware shows extremely sophisticated network abilities

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#101]
https://www.globenewswire.com/news-release/2022/06/02/2455397/0/en/Kaspersky-WinDealer-malware-shows-extremely-sophisticated-network-abilities.html

**Comment by CyberMonitor** [comment]
thank the info, update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.06.02.WinDealer
