### ISSUE TITLE
Add report

### ISSUE THREAD

**Issue by ignacioj** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#105]
Hello, this report is interesting, would you mind to include it?

https://www.recordedfuture.com/exposing-tag-53-credential-harvesting-infrastructure-for-russia-aligned-espionage-operations

Thank you!

**Comment by CyberMonitor** [comment]
Thank the data. Update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.12.05.TAG-53_Russia
