### ISSUE TITLE
Dark Pink New APT hitting Asia-Pacific, Europe that goes deeper and darker

### ISSUE THREAD

**Issue by ignacioj** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#107]
https://blog.group-ib.com/dark-pink-apt

**Comment by CyberMonitor** [comment]
thank the info
update done at https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/blob/master/2023/2023.01.11.Dark_Pink_APT
