### ISSUE TITLE
Tracking the Evolution of GOOTLOADER Operations

### ISSUE THREAD

**Issue by ignacioj** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#109]
https://www.mandiant.com/resources/blog/tracking-evolution-gootloader-operations

**Comment by CyberMonitor** [comment]
thanks

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/blob/master/2023/2023.01.26.GOOTLOADER_Operations
