### ISSUE TITLE
Hogfish (APT10) Redleaves campaign

### ISSUE THREAD

**Issue by zappeee** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#11]
https://www.accenture.com/t20180423T055005Z__w__/us-en/_acnmedia/PDF-76/Accenture-Hogfish-Threat-Analysis.pdf

**Comment by CyberMonitor** [comment]
Thank you the contribute 

There is in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2018/2018.04.23.HOGFISH_REDLEAVES_CAMPAIGN now
