### ISSUE TITLE
Me no want 

### ISSUE THREAD

**Issue by Aj084v** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#117]
You probably wanted a `case` here.
```suggestion
	local _arch
	case "$TERMUX_ARCH" in
		'aarch64') _arch='arm64';;
		'arm')     _arch='arm';;
		'x86_64')  _arch='x64';;
		'i686')    _arch='x86';;
		*) termux_error_exit "Architecture not supported by build system"
	esac
```

_Originally posted by @TomJo2000 in https://github.com/termux/termux-packages/pull/20712#discussion_r1658463234_
**```
- > `@rhaist @actions-user 
```**

**Comment by TomJo2000** [comment]
What the actual fuck?

**Comment by minhnq1618** [comment]
what the fuck is this ?

**Comment by CyberMonitor** [comment]
This is not the case for this project
