### ISSUE TITLE
Add Goldfin campaign

### ISSUE THREAD

**Issue by bartblaze** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#13]
Link: 
https://www.accenture.com/us-en/blogs/blogs-goldfin-security-alert

Direct link (PDF):
https://www.accenture.com/t20180807T100707Z__w__/us-en/_acnmedia/PDF-83/Accenture-Goldfin-Security-Alert-1.pdf

Thanks!

**Comment by CyberMonitor** [comment]
Dear Bartblaze, 

  Thank for your sharing,  I put to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2018/2018.08.02.Goldfin_Security_Alert already. 

Sincerely yours,
