### ISSUE TITLE
New blog by Trend Micro SLUB Backdoor

### ISSUE THREAD

**Issue by wbbigdave** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#14]
https://blog.trendmicro.com/trendlabs-security-intelligence/new-slub-backdoor-uses-github-communicates-via-slack/

See above for the link to the new blog post.

**Comment by CyberMonitor** [comment]
Thank you the sharing.  I push into this https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2019/2019.03.07.SLUB_Backdoor
