### ISSUE TITLE
New Cyber Criminal Campaigns

### ISSUE THREAD

**Issue by marcoramilli** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#18]
Maybe it would be nice to keep track to even those CyberCriminal Campaigns ?

- **TA-505 Cybercrime on System Integrator Companies**: https://marcoramilli.com/2019/11/12/ta-505-cybercrime-on-system-integrator-companies/  

- **SWEED Targeting Precision Engineering Companies in Italy**: https://marcoramilli.com/2019/10/28/sweed-targeting-precision-engineering-companies-in-italy/

- **Is Emotet gang targeting companies with external SOC?**: https://marcoramilli.com/2019/10/14/is-emotet-gang-targeting-companies-with-external-soc/

- **Ransomware, Trojan and Miner together against “PIK-Group"**: https://marcoramilli.com/2019/02/28/ransomware-trojan-and-miner-together-against-pik-group/

- **MartyMcFly Malware: Targeting Naval Industry**: https://marcoramilli.com/2018/10/17/martymcfly-malware-targeting-naval-industry/**

**Comment by CyberMonitor** [comment]
Thank the Campaign data.  Updated in the newest commit.
