### ISSUE TITLE
Mapping between hashes and campaigns

### ISSUE THREAD

**Issue by hgascon** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#2]
Is there any mapping available between hashes of binaries mentioned in the reports and the campaigns they are part of? If not for this repository, what about others you might know?

**Comment by CyberMonitor** [comment]
Most of them are in the Threat Correction System like https://www.alienvault.com/. 
I am not sure the focus place of the 'Mapping-Campaign-Hash' repository. 

Maybe you can try to use AlienVault API to mapping this.  👍
