### ISSUE TITLE
New ClearSky Report - Charming Kitten

### ISSUE THREAD

**Issue by ssnkhan** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#24]
The Kittens Are Back in Town 3
Charming Kitten Campaign Evolved and Deploying Spear-Phishing link by WhatsApp

https://www.clearskysec.com/wp-content/uploads/2020/08/The-Kittens-are-Back-in-Town-3.pdf

**Comment by CyberMonitor** [comment]
Thank ssnkhan

update here: https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.08.27.Kittens_Are_Back
