### ISSUE TITLE
The Lazarus Constellation - Lexfo Whitepaper

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#26]
https://blog.lexfo.fr/ressources/Lexfo-WhitePaper-The_Lazarus_Constellation.pdf

**Comment by CyberMonitor** [comment]
Thank you!   put in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.02.19_The_Lazarus_Constellation. 👍
