### ISSUE TITLE
MuddyWater’s (Iranian APT) Offensive Attack Against Israeli Organizations

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#30]
Release Date: October 2020

https://www.clearskysec.com/wp-content/uploads/2020/10/Operation-Quicksand.pdf

**Comment by CyberMonitor** [comment]
thanks!!

update in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/blob/master/2020/2020.10.15_Operation_Quicksand_MuddyWater%E2%80%99s_Offensive_Attack_Against_Israeli/2020.10.15_Operation_Quicksand_MuddyWater%E2%80%99s_Offensive_Attack_Against_Israeli.pdf
