### ISSUE TITLE
CISA Alert AA20-301A: North Korean Advanced Persistent Threat Focus: Kimsuky

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#31]
https://us-cert.cisa.gov/sites/default/files/publications/TLP-WHITE_AA20-301A_North_Korean_APT_Focus_Kimsuky.pdf

**Comment by CyberMonitor** [comment]
Thank you!

Update in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.10.27_AA20-301A.North_Korean_APT
