### ISSUE TITLE
Greetings from Lazarus: Anatomy of a cyber espionage campaign

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#33]
https://www.hvs-consulting.de/lazarus-report/

**Comment by CyberMonitor** [comment]
Thanks the info,  update here: https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.12.15.Lazarus_Campaign
