### ISSUE TITLE
Lazarus covets COVID-19-related intelligence

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#34]
https://securelist.com/lazarus-covets-covid-19-related-intelligence/99906/

**Comment by CyberMonitor** [comment]
Thanks for the update:  here is. https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.12.23.Lazarus_COVID-19
