### ISSUE TITLE
Add SolarWinds report from Recorded Future

### ISSUE THREAD

**Issue by like-a-freedom** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#36]
SOLARWINDS ATTRIBUTION: Are We Getting Ahead of Ourselves? An Analysis of UNC2452 Attribution.

https://go.recordedfuture.com/hubfs/reports/pov-2020-1230.pdf

**Comment by CyberMonitor** [comment]
Thank the data, update in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.12.30.SolarWinds_Attribution now
