### ISSUE TITLE
Charming Kitten’s Christmas Gift

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#37]
https://blog.certfa.com/posts/charming-kitten-christmas-gift/

**Comment by CyberMonitor** [comment]
Thank the contribution. Add to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.01.08.Charming_Kitten_Christmas_Gift
