### ISSUE TITLE
Study of the APT attacks on state institutions in Kazakhstan and Kyrgyzstan

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#38]
https://st.drweb.com/static/new-www/news/2020/july/Study_of_the_APT_attacks_on_state_institutions_in_Kazakhstan_and_Kyrgyzstan_en.pdf

**Comment by CyberMonitor** [comment]
Thank you!!!   collected in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.07.20.APT_attacks_Kazakhstan_Kyrgyzstan now
