### ISSUE TITLE
"Lebanese Cedar" APT Global Lebanese Espionage Campaign Leveraging Web Servers

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#39]
https://www.clearskysec.com/wp-content/uploads/2021/01/Lebanese-Cedar-APT.pdf

**Comment by CyberMonitor** [comment]
Thank you for the info,  put in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.01.28.Lebanese_Cedar_APT now.
