### ISSUE TITLE
Domestic Kitten – An Inside Look at the Iranian Surveillance Operations

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#42]
https://research.checkpoint.com/2021/domestic-kitten-an-inside-look-at-the-iranian-surveillance-operations/

**Comment by CyberMonitor** [comment]
Thank you!!! 

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.02.08.Domestic_Kitten
