### ISSUE TITLE
Could we push these reports to our MISP/OpenCTI instance 

### ISSUE THREAD

**Issue by raysnider** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#43]
We have a threat intel platform that we are currently using (MISP and OpenCTI), is it possible to ingest these reports into our TIPs? If so, can you help me out with this.

I appreciate the help
-Ray

**Comment by CyberMonitor** [comment]
Hi Ray, 

  Look interesting. Could you tell me how to do it?   
Thanks

Sincerely yours,
