### ISSUE TITLE
Error: 2015/2015.06.28.APT_on_Taiwan/DTL-06282015-01.pdf

### ISSUE THREAD

**Issue by rhaist** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#44]
The file `2015/2015.06.28.APT_on_Taiwan/DTL-06282015-01.pdf` is containing HTML code.
Probably a download failure.
The correct file can be downloaded here: https://github.com/DragonThreatLabs/IntelReports

**Comment by CyberMonitor** [comment]
fixed
