### ISSUE TITLE
XMRig-based CoinMiners by Blue Mockingbird 

### ISSUE THREAD

**Issue by laciKE** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#45]
Hello, not sure if you are interested already is one report about Mockingbirds, however, there is another one older case study about same threat actor, focused more on malware analysis, prepared in May 2020 by LIFARS, published on Jun 01 2020.

https://lifars.com/knowledge-center/xmrig-based-coinminer-bluemockingbird-group/

And malware samples and any.run analysis mentioned during talk at  DEFCON 28:
https://app.any.run/tasks/318e4886-35da-4d71-8610-fb6b3964d04b/

**Comment by CyberMonitor** [comment]
Thank the report, I put in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.06.01.Blue_Mockingbird_Group now
