### ISSUE TITLE
The Story of Jian – How APT31 Stole and Used an Unknown Equation Group 0-Day

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#47]
https://research.checkpoint.com/2021/the-story-of-jian/

**Comment by CyberMonitor** [comment]
Thanks!!!  update here. https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.02.22.APT31_Equation_Group
