### ISSUE TITLE
Ocean Lotus -> Click and Bait: Vietnamese Human Rights Defenders Targeted with Spyware Attacks

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#48]
https://www.amnesty.org/en/latest/research/2021/02/click-and-bait-vietnamese-human-rights-defenders-targeted-with-spyware-attacks/

**Comment by CyberMonitor** [comment]
thanks,  update into https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.02.24.Click_and_Bait
