### ISSUE TITLE
Lazarus targets defense industry with ThreatNeedle

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#50]
https://ics-cert.kaspersky.com/media/Kaspersky-ICS-CERT-Lazarus-targets-defense-industry-with-Threatneedle-En.pdf

**Comment by CyberMonitor** [comment]
update into https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.02.25.Lazarus_ThreatNeedle

thanks
