### ISSUE TITLE
China-linked Group RedEcho Targets the Indian Power Sector Amid Heightened Border Tensions

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#52]
https://www.recordedfuture.com/redecho-targeting-indian-power-sector/

**Comment by CyberMonitor** [comment]
Thanks!!  update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.02.28.RedEcho_APT
