### ISSUE TITLE
BitDefender: FIN8 Returns with Improved BADHATCH Toolkit

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#53]
https://www.bitdefender.com/files/News/CaseStudies/study/394/Bitdefender-PR-Whitepaper-BADHATCH-creat5237-en-EN.pdf

**Comment by CyberMonitor** [comment]
Thank you!    Update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.03.10.FIN8_BADHATCH_Toolkit
