### ISSUE TITLE
Lazarus APT conceals malicious code within BMP image to drop its RAT

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#55]
https://blog.malwarebytes.com/malwarebytes-news/2021/04/lazarus-apt-conceals-malicious-code-within-bmp-file-to-drop-its-rat/

**Comment by CyberMonitor** [comment]
thank the data.  update into 2021.04.19.Lazarus_APT_conceals_malicious_code_within_BMP_image_to_drop_its_RAT.pdf
