### ISSUE TITLE
NCSC: Further TTPs associated with SVR cyber actors

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#56]
https://www.ncsc.gov.uk/files/Advisory%20Further%20TTPs%20associated%20with%20SVR%20cyber%20actors.pdf

**Comment by CyberMonitor** [comment]
thank the update
update done in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.05.07.SVR_TTPs
