### ISSUE TITLE
Attributing Attacks Against Crypto Exchanges to LAZARUS – North Korea

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#58]
https://www.clearskysec.com/wp-content/uploads/2021/05/CryptoCore-Lazarus-Clearsky.pdf

**Comment by CyberMonitor** [comment]
Thanks the data, update done: https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.05.01.CryptoCore-Lazarus
