### ISSUE TITLE
Combojack malware - 5mar18

### ISSUE THREAD

**Issue by P4rs3R** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#6]
[Combojack malware - analysis by Palo Alto Networks Unit42](https://researchcenter.paloaltonetworks.com/2018/03/unit42-sure-ill-take-new-combojack-malware-alters-clipboards-steal-cryptocurrency/)

**Comment by CyberMonitor** [comment]
Thanks!!!   Updated already

Mar 05 - [Palo Alto Networks] Sure, I’ll take that! New ComboJack Malware Alters Clipboards to Steal Cryptocurrency | Local
