### ISSUE TITLE
Ferocious Kitten: 6 years of covert surveillance in Iran

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#60]
https://securelist.com/ferocious-kitten-6-years-of-covert-surveillance-in-iran/102806/

**Comment by CyberMonitor** [comment]
Thank the info

The data update into https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.06.16.Ferocious_Kitten
