### ISSUE TITLE
Threat Activity Group RedFoxtrot Linked to China’s PLA Unit 69010

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#61]
https://www.recordedfuture.com/redfoxtrot-china-pla-targets-bordering-asian-countries/

**Comment by CyberMonitor** [comment]
thanks the source, update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.06.16.RedFoxtrot_APT_PLA_69010
