### ISSUE TITLE
IndigoZebra APT continues to attack Central Asia with evolving tools

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#62]
https://research.checkpoint.com/2021/indigozebra-apt-continues-to-attack-central-asia-with-evolving-tools/

**Comment by CyberMonitor** [comment]
Thank you!!   update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.07.01.IndigoZebra_APT
