### ISSUE TITLE
AT&T: Lazarus campaign TTPs and evolution

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#63]
https://cybersecurity.att.com/blogs/labs-research/lazarus-campaign-ttps-and-evolution

**Comment by CyberMonitor** [comment]
Thank you!!!

Update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.07.06.Lazarus_TTPs_evolution
