### ISSUE TITLE
Alert (AA21-200A): Tactics, Techniques, and Procedures of Indicted APT40 Actors Associated with China’s MSS Hainan State Security Department

### ISSUE THREAD

**Issue by herebepanda** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#64]
https://us-cert.cisa.gov/sites/default/files/publications/CSA_TTPs-of-Indicted-APT40-Actors-Associated-with-China-MSS-Hainan-State-Security-Department.pdf

**Comment by CyberMonitor** [comment]
thanks,  update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.07.19.APT40_TTP
