### ISSUE TITLE
I Knew You Were Trouble: TA456 Targets Defense Contractor with Alluring Social Media Persona

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#65]
https://www.proofpoint.com/us/blog/threat-insight/i-knew-you-were-trouble-ta456-targets-defense-contractor-alluring-social-media

**Comment by CyberMonitor** [comment]
Thank you very much!

Update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.07.28.TA456
