### ISSUE TITLE
News about APT 15 "Mirage"

### ISSUE THREAD

**Issue by P4rs3R** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#7]
Update about APT 15 "Mirage"
* [NCC Group link 1](https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blogs/2018/march/apt15-is-alive-and-strong-an-analysis-of-royalcli-and-royaldns/)
* [NCC Group link 2](https://www.nccgroup.trust/uk/about-us/newsroom-and-events/press-releases/2018/march/new-tools-uncovered-from-hacking-group-apt15/)

**Comment by CyberMonitor** [comment]
Thanks

added on 
Mar 09 - [NCC] APT15 is alive and strong: An analysis of RoyalCli and RoyalDNS | Local
