### ISSUE TITLE
CrowdStrike - Nowhere to hide

### ISSUE THREAD

**Issue by SleepyLctl** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#71]
https://www.crowdstrike.com/resources/reports/threat-hunting-report-2021/

**Comment by CyberMonitor** [comment]
Thank you!!!

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/blob/master/Report/CrowdStrike/Report2021ThreatHunting.pdf
