### ISSUE TITLE
Missin RecordedFuture Reports

### ISSUE THREAD

**Issue by SleepyLctl** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#72]
Hi, I also see missing RF reports like: https://www.recordedfuture.com/russian-state-connections-criminal-actors/

Do you still keep this repo up to date? I see you still do?

Thanks for maintanence/

**Comment by CyberMonitor** [comment]
Dear Sir, 

  Yes.. I try to keep this repo up to date.  
  And thank you for help to collect the report. 

  The Recorded Future report is repo here now: https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.09.09.Dark_Covenant

Sincerely yours,
