### ISSUE TITLE
Operation GhostShell: Novel RAT Targets Global Aerospace and Telecoms Firms

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#74]
https://www.cybereason.com/blog/operation-ghostshell-novel-rat-targets-global-aerospace-and-telecoms-firms

**Comment by CyberMonitor** [comment]
Thank you!!!!

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.10.06.Operation_GhostShell
