### ISSUE TITLE
JUMPING THE AIR GAP: 15 years of nation-state effort

### ISSUE THREAD

**Issue by jorritfolmer** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#79]
https://www.welivesecurity.com/wp-content/uploads/2021/12/eset_jumping_the_air_gap_wp.pdf

**Comment by CyberMonitor** [comment]
thank you!!!

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.12.11.Jumping_the_air_gap
