### ISSUE TITLE
ZScaler - New DarkHotel APT attack chain identified

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#80]
https://www.zscaler.com/blogs/security-research/new-darkhotel-apt-attack-chain-identified

**Comment by CyberMonitor** [comment]
thank you!!

Update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.12.16.New_DarkHotel_APT
