### ISSUE TITLE
Conti cyber attack on the HSE

### ISSUE THREAD

**Issue by jorritfolmer** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#81]
https://www.hse.ie/eng/services/publications/conti-cyber-attack-on-the-hse-full-report.pdf

**Comment by CyberMonitor** [comment]
update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.12.03.Conti_Attack_HSE

Thank you very much
