### ISSUE TITLE
MoonBounce: the dark side of UEFI firmware

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#84]
https://securelist.com/moonbounce-the-dark-side-of-uefi-firmware/105468/

**Comment by CyberMonitor** [comment]
thank the data!

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.01.20.MoonBounce
