### ISSUE TITLE
FIN13: A Cybercriminal Threat Actor Focused on Mexico

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#85]
https://www.mandiant.com/resources/fin13-cybercriminal-mexico

**Comment by CyberMonitor** [comment]
Thank the info

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2021/2021.12.07.FIN13
