### ISSUE TITLE
Shuckworm Continues Cyber-Espionage Attacks Against Ukraine

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#89]
https://symantec-enterprise-blogs.security.com/blogs/threat-intelligence/shuckworm-gamaredon-espionage-ukraine

**Comment by CyberMonitor** [comment]
thank the info
update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.01.31.Shuckworm_APT
