### ISSUE TITLE
Iranian APT MuddyWater targets Turkish users via malicious PDFs, executables

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#90]
https://blog.talosintelligence.com/2022/01/iranian-apt-muddywater-targets-turkey.html

**Comment by CyberMonitor** [comment]
update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.01.31.MuddyWater_Turkish
