### ISSUE TITLE
PowerLess Trojan: Iranian APT Phosphorus Adds New PowerShell Backdoor for Espionage

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#91]
https://www.cybereason.com/blog/powerless-trojan-iranian-apt-phosphorus-adds-new-powershell-backdoor-for-espionage

**Comment by CyberMonitor** [comment]
update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.02.01.Phosphorus_APT

thanks
