### ISSUE TITLE
(Ex)Change of Pace: UNC2596 Observed Leveraging Vulnerabilities to Deploy Cuba Ransomware

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#94]
https://www.mandiant.com/resources/unc2596-cuba-ransomware

**Comment by CyberMonitor** [comment]
update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.02.23.UNC2596

thanks
