### ISSUE TITLE
SecureList: APT trends report Q1 2022

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#96]
https://securelist.com/apt-trends-report-q1-2022/106351/

**Comment by CyberMonitor** [comment]
Thank the report,  update in https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/blob/master/Report/Kaspersky/APT_trends_report_Q2_2022_Securelist.pdf
