### ISSUE TITLE
Mustang Panda deploys a new wave of malware targeting Europe

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#98]
https://blog.talosintelligence.com/2022/05/mustang-panda-targets-europe.html

**Comment by CyberMonitor** [comment]
thank the info

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.05.05.Mustang_Panda_Europe
