### ISSUE TITLE
Bitter APT adds Bangladesh to their targets

### ISSUE THREAD

**Issue by d4rk-d4nph3** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#99]
https://blog.talosintelligence.com/2022/05/bitter-apt-adds-bangladesh-to-their.html

**Comment by CyberMonitor** [comment]
thanks

update to https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2022/2022.05.11.Bitter_APT_Bangladesh
